### PR TITLE
feat: Implement solution for 242. Valid Anagram and update README

### PR DESCRIPTION
**Pull request by shreyasrajiv327**
This commit adds a solution for the "Valid Anagram" problem (LeetCode 242) using hash maps to count character frequencies. 

- Implemented the `isAnagram` method to compare two strings by their character counts.
- Added example test cases to demonstrate the functionality.
- Updated the README.md file with problem details, approach explanation, and code implementation.

The solution checks if two strings are anagrams by comparing the frequency of each character in both strings.

### CODE REVIEW

**Comment by iamwatchdogs** [comment]
@shreyasrajiv327 Please check the linting results and fix the issue and I'll merge your pull request...

**Comment by shreyasrajiv327** [comment]
@iamwatchdogs I have fixed the issue

**Comment by iamwatchdogs** [comment]
@shreyasrajiv327 There're still few issue that are required to be resolved... Please checkout the [Files Changed](https://github.com/Grow-with-Open-Source/DSA/pull/5/files) section for more info.

**Comment by iamwatchdogs** [comment]
@shreyasrajiv327 I think there are some formatting issue.. You can checkout the formatted version from the recent workflow that given you formatted output... [linter / java-linter / need-help (pull_request)](https://github.com/Grow-with-Open-Source/DSA/actions/runs/10247900725/job/28348050048?pr=5) -> Show Diffs and exit

**Review by iamwatchdogs — APPROVED** [review]
Reviewed and Approved by @iamwatchdogs.

**Comment by iamwatchdogs** [comment]
Thank you for contribution @shreyasrajiv327, You can review you work on [GitHub pages](https://grow-with-open-source.github.io/DSA/).

**Comment by iamwatchdogs** [comment]
Please make sure to post your contributions on Linkedin while tagging @Grow-With-Open-Source...

**Pull request merged**
